<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Brut.FamilyTree</AssemblyName>
    <RootNamespace>Brut.FamilyTree</RootNamespace>

    <GameFolder>D:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord</GameFolder>
    <ModuleFolder>$(GameFolder)\Modules\Brut.FamilyTree</ModuleFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ScreenSystem">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine.GauntletUI">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Engine.GauntletUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SandBox.GauntletUI">
      <HintPath>$(GameFolder)\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SandBox.View">
      <HintPath>$(GameFolder)\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToModules" AfterTargets="Build">
    <MakeDir Directories="$(ModuleFolder)\bin\Win64_Shipping_Client" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModuleFolder)\bin\Win64_Shipping_Client" />
    <Copy SourceFiles="SubModule.xml" DestinationFolder="$(ModuleFolder)" />
    <!-- Copy GUI folder -->
    <ItemGroup>
      <GUIFiles Include="_Module\GUI\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(GUIFiles)" DestinationFolder="$(ModuleFolder)\GUI\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
